[MULTILINE_PARSER]
    name deadlock_innodb_start
    type regex
    flush_timeout 5000
    rule    "start_state" "/(^[0-9]{4}-[0-9]{2}-[0-9]{2}\s[0-9]{2}:[0-9]{2}:[0-9]{2}\s[0-9]+\s\[.*\]\s)(InnoDB:\s$|InnoDB:$)/" "cont"
    rule    "cont"  "/(^$|^[A-Za-z]+.*|^\s[0-9]+:.*;;|^\*\*\*.*$)/" "cont"

[MULTILINE_PARSER]
    name deadlock_innodb_start_empty
    type regex
    flush_timeout 5000
    rule    "start_state" "/(^[0-9]{4}-[0-9]{2}-[0-9]{2}\s[0-9]{2}:[0-9]{2}:[0-9]{2}\s[0-9]+\s\[.*\]\s)(InnoDB:\s$|InnoDB:$)/" "cont"
    rule    "cont"  "/(^$|^[A-Za-z]+.*|^\s[0-9]+:.*;;|^\*\*\*.*$)/" "cont"

[MULTILINE_PARSER]
    name deadlock_innodb_waiting
    type regex
    flush_timeout 5000
    rule    "start_state" "/(^[0-9]{4}-[0-9]{2}-[0-9]{2}\s[0-9]{2}:[0-9]{2}:[0-9]{2}\s[0-9]+\s\[.*\]\sInnoDB.*WAITING FOR THIS LOCK)/" "cont"
    rule    "cont"  "/(^$|^[A-Za-z]+.*|^\s[0-9]+:.*;;|^\*\*\*.*$)/" "cont"

[MULTILINE_PARSER]
    name deadlock_innodb_conf_with
    type regex
    flush_timeout 5000
    rule    "start_state" "/(^[0-9]{4}-[0-9]{2}-[0-9]{2}\s[0-9]{2}:[0-9]{2}:[0-9]{2}\s[0-9]+\s\[.*\]\sInnoDB.*CONFLICTING WITH)/" "cont"
    rule    "cont"  "/(^$|^[A-Za-z]+.*|^\s[0-9]+:.*;;|^\*\*\*.*$)/" "cont"

