[PARSER]
    Name mariadb_server_audit
    Format regex
    Regex ^(?<date>\d{4}\d{2}\d{2})\s(?<time>\d{2}:\d{2}:\d{2}),(?<database_host>[A-Z|a-z]+),(?<username>[A-Z|a-z]+),(?<username_host>[A-Z|a-z]+),(?<connection_id>\d+),(?<query_id>\d+),(?<event>[A-Z|a-z]+),(?<database>[A-Z|a-z]*),(?<query>'.*'|\S*),(?<error_number>\d?)

[MULTILINE_PARSER]
    name mariadb_error_log
    type regex
    flush_timeout 5000
    rule    "start_state" "/(^\d{4}-\d{2}-\d{2}\s\d{2}:\d{2}:\d{2}\s\d+\s\[.*\]).*$/" "cont"
    rule    "cont"  "/(^$|^[A-Za-z]+.*|^\s\d+:.*;;|^\*\*\*.*$)/" "cont"

[MULTILINE_PARSER]
    name slow_query_file
    type regex
    flush_timeout 5000
    rule "start_state" "/(^#\s)(Time|User)/" "cont"
    rule "cont" "/^(?!#\sTime).*/" "cont"
