[SERVICE]
    Flush        1
    Log_Level    info

[INPUT]
    Name         tail
    Path         /var/log/mariadb/audit.log
    Tag          audit
    DB           /var/log/audit_tail.db
    Mem_Buf_Limit 5MB
    Skip_Long_Lines Off

[OUTPUT]
    Name         s3
    Match        audit
    bucket       bucket_name
    region       eu-central-1
    total_file_size 100M
    upload_timeout 10m 
    store_dir    /var/log/fluentbit/s3
    s3_key_format /logs/%Y/%m/%d/%H/%M/%S-mariadb-audit-logs.gz
    s3_key_format_tag_delimiters .
    compression  gzip
    tls          On
    tls.verify   Off
