[SERVICE]
        Daemon off
        log_level info


[OUTPUT]
        Name stdout
        Match mariadb.*

[OUTPUT]
        Name forward
        Match mariadb.*

[FILTER]
        Name wasm
        match mariadb.error
        WASM_Path mariadb_filters.wasm
        Function_Name filter_error_log
        accessible_paths .,/opt/fluent-bit/bin/
