#!/usr/bin/env bash

JOURNAL_MARIADB="${JOURNAL_MARIADB:=mariadb}"
JOURNAL_AUDIT="${JOURNAL_AUDIT:=mysql-server_auditing}"

BACKUP_ROOT="${BACKUP_ROOT:=/mnt/data/backups}"
BACKUP_DATE="${BACKUP_DATE:=$(date +'%d%m%Y-%H%M%S')}"
BACKUP_NAME="${BACKUP_FILE:=full-bkp-${BACKUP_DATE}}"
BACKUP_FILE="${BACKUP_FILE:=${BACKUP_ROOT}/${BACKUP_NAME}.gz}"

DUMP_OPTS="${DUMP_OPTS:=--all-databases --single-transaction --master-data=2 --routines --triggers --events}"
DUMP_NAME="${DUMP_NAME:=dump-${BACKUP_DATE}}"
DUMP_FILE="${DUMP_FILE:=${BACKUP_ROOT}/${DUMP_NAME}}"


stop_slave() {
    mariadb --show-warnings -NBe "STOP SLAVE"
}

start() {
    systemctl start mariadb
}


stop() {
    systemctl stop mariadb
}

status() {
    systemctl status mariadb
}

slave() {
    mariadb -E -e "show slave status"
}

master() {
    mariadb -e "show master status"
}

slaves() {
    mariadb -e "show slave hosts"
}

error_log() {
    journalctl -u ${JOURNAL_MARIADB} -xe
}

audit_log() {
    journalctl -u ${JOURNAL_MARIADB} -xe
}

backup() {
    mariadb-backup --backup --stream=mbstream | gzip > ${BACKUP_FILE}
}

dump() {
    mariadb-dump ${DUMP_OPTS} | gzip > ${DUMP_FILE}
}

print_usage() {
    echo "TODO"
    exit 0
}


case "${1}" in
    stop)
        stop
        ;;
    start)
        start
        ;;
    status)
        status
        ;;
    backup)
        backup
        ;;
    dump)
        dump
        ;;
    audit-log)
       audit_log 
        ;;
    error-log)
       error_log 
        ;;
    help)
       print_usage 
        ;;
    "-h")
       print_usage 
        ;;
    *)
       mariadb 
        ;;
esac

exit 0
